### ISSUE TITLE
Addition of All Contributors Photos in the Readme | As a Token of Appreciation for Their Hard Work

### ISSUE THREAD

**Issue by Shariq2003** [StephCurry07/Ether-Wheels#24]
I want to add all the contributor's photos in the readme file to showcases as a token of appreciation for their hard work.
I am going to add a script that will dynamically fetch the contributors.

![image](https://github.com/user-attachments/assets/a9989fe5-911f-44de-8719-cd4ae7a9d65e)

Like this

**Comment by StephCurry07** [comment]
It exists already...Give it a look
